[MeasureDriveLabelA]
Measure=FreeDiskSpace
Drive=A:
Group=MeasureDriveA
Label=1
UpdateDivider=-1

[MeasureDriveTotalA]
Measure=FreeDiskSpace
Drive=A:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveA"][!EnableMeasureGroup "MeasureDriveA"][!SetOptionGroup DriveA Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveA"][!DisableMeasureGroup "MeasureDriveA"][!SetOptionGroup DriveA Y 0R]
UpdateDivider=-1

[MeasureDriveFreeA]
Measure=FreeDiskSpace
Drive=A:
Group=MeasureDriveA
UpdateDivider=5

[MeasureDriveBusyA]
Measure=FreeDiskSpace
Drive=A:
Group=MeasureDriveA
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelB]
Measure=FreeDiskSpace
Drive=B:
Group=MeasureDriveB
Label=1
UpdateDivider=-1

[MeasureDriveTotalB]
Measure=FreeDiskSpace
Drive=B:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveB"][!EnableMeasureGroup "MeasureDriveB"][!SetOptionGroup DriveB Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveB"][!DisableMeasureGroup "MeasureDriveB"][!SetOptionGroup DriveB Y 0R]
UpdateDivider=-1

[MeasureDriveFreeB]
Measure=FreeDiskSpace
Drive=B:
Group=MeasureDriveB
UpdateDivider=5

[MeasureDriveBusyB]
Measure=FreeDiskSpace
Drive=B:
Group=MeasureDriveB
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelC]
Measure=FreeDiskSpace
Drive=C:
Group=MeasureDriveC
Label=1
UpdateDivider=-1

[MeasureDriveTotalC]
Measure=FreeDiskSpace
Drive=C:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveC"][!EnableMeasureGroup "MeasureDriveC"][!SetOptionGroup DriveC Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveC"][!DisableMeasureGroup "MeasureDriveC"][!SetOptionGroup DriveC Y 0R]
UpdateDivider=-1

[MeasureDriveFreeC]
Measure=FreeDiskSpace
Drive=C:
Group=MeasureDriveC
UpdateDivider=5

[MeasureDriveBusyC]
Measure=FreeDiskSpace
Drive=C:
Group=MeasureDriveC
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelD]
Measure=FreeDiskSpace
Drive=D:
Group=MeasureDriveD
Label=1
UpdateDivider=-1

[MeasureDriveTotalD]
Measure=FreeDiskSpace
Drive=D:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveD"][!EnableMeasureGroup "MeasureDriveD"][!SetOptionGroup DriveD Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveD"][!DisableMeasureGroup "MeasureDriveD"][!SetOptionGroup DriveD Y 0R]
UpdateDivider=-1

[MeasureDriveFreeD]
Measure=FreeDiskSpace
Drive=D:
Group=MeasureDriveD
UpdateDivider=5

[MeasureDriveBusyD]
Measure=FreeDiskSpace
Drive=D:
Group=MeasureDriveD
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelE]
Measure=FreeDiskSpace
Drive=E:
Group=MeasureDriveE
Label=1
UpdateDivider=-1

[MeasureDriveTotalE]
Measure=FreeDiskSpace
Drive=E:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveE"][!EnableMeasureGroup "MeasureDriveE"][!SetOptionGroup DriveE Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveE"][!DisableMeasureGroup "MeasureDriveE"][!SetOptionGroup DriveE Y 0R]
UpdateDivider=-1

[MeasureDriveFreeE]
Measure=FreeDiskSpace
Drive=E:
Group=MeasureDriveE
UpdateDivider=5

[MeasureDriveBusyE]
Measure=FreeDiskSpace
Drive=E:
Group=MeasureDriveE
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelF]
Measure=FreeDiskSpace
Drive=F:
Group=MeasureDriveF
Label=1
UpdateDivider=-1

[MeasureDriveTotalF]
Measure=FreeDiskSpace
Drive=F:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveF"][!EnableMeasureGroup "MeasureDriveF"][!SetOptionGroup DriveF Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveF"][!DisableMeasureGroup "MeasureDriveF"][!SetOptionGroup DriveF Y 0R]
UpdateDivider=-1

[MeasureDriveFreeF]
Measure=FreeDiskSpace
Drive=F:
Group=MeasureDriveF
UpdateDivider=5

[MeasureDriveBusyF]
Measure=FreeDiskSpace
Drive=F:
Group=MeasureDriveF
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelG]
Measure=FreeDiskSpace
Drive=G:
Group=MeasureDriveG
Label=1
UpdateDivider=-1

[MeasureDriveTotalG]
Measure=FreeDiskSpace
Drive=G:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveG"][!EnableMeasureGroup "MeasureDriveG"][!SetOptionGroup DriveG Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveG"][!DisableMeasureGroup "MeasureDriveG"][!SetOptionGroup DriveG Y 0R]
UpdateDivider=-1

[MeasureDriveFreeG]
Measure=FreeDiskSpace
Drive=G:
Group=MeasureDriveG
UpdateDivider=5

[MeasureDriveBusyG]
Measure=FreeDiskSpace
Drive=G:
Group=MeasureDriveG
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelH]
Measure=FreeDiskSpace
Drive=H:
Group=MeasureDriveH
Label=1
UpdateDivider=-1

[MeasureDriveTotalH]
Measure=FreeDiskSpace
Drive=H:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveH"][!EnableMeasureGroup "MeasureDriveH"][!SetOptionGroup DriveH Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveH"][!DisableMeasureGroup "MeasureDriveH"][!SetOptionGroup DriveH Y 0R]
UpdateDivider=-1

[MeasureDriveFreeH]
Measure=FreeDiskSpace
Drive=H:
Group=MeasureDriveH
UpdateDivider=5

[MeasureDriveBusyH]
Measure=FreeDiskSpace
Drive=H:
Group=MeasureDriveH
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelI]
Measure=FreeDiskSpace
Drive=I:
Group=MeasureDriveI
Label=1
UpdateDivider=-1

[MeasureDriveTotalI]
Measure=FreeDiskSpace
Drive=I:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveI"][!EnableMeasureGroup "MeasureDriveI"][!SetOptionGroup DriveI Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveI"][!DisableMeasureGroup "MeasureDriveI"][!SetOptionGroup DriveI Y 0R]
UpdateDivider=-1

[MeasureDriveFreeI]
Measure=FreeDiskSpace
Drive=I:
Group=MeasureDriveI
UpdateDivider=5

[MeasureDriveBusyI]
Measure=FreeDiskSpace
Drive=I:
Group=MeasureDriveI
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelJ]
Measure=FreeDiskSpace
Drive=J:
Group=MeasureDriveJ
Label=1
UpdateDivider=-1

[MeasureDriveTotalJ]
Measure=FreeDiskSpace
Drive=J:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveJ"][!EnableMeasureGroup "MeasureDriveJ"][!SetOptionGroup DriveJ Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveJ"][!DisableMeasureGroup "MeasureDriveJ"][!SetOptionGroup DriveJ Y 0R]
UpdateDivider=-1

[MeasureDriveFreeJ]
Measure=FreeDiskSpace
Drive=J:
Group=MeasureDriveJ
UpdateDivider=5

[MeasureDriveBusyJ]
Measure=FreeDiskSpace
Drive=J:
Group=MeasureDriveJ
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelK]
Measure=FreeDiskSpace
Drive=K:
Group=MeasureDriveK
Label=1
UpdateDivider=-1

[MeasureDriveTotalK]
Measure=FreeDiskSpace
Drive=K:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveK"][!EnableMeasureGroup "MeasureDriveK"][!SetOptionGroup DriveK Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveK"][!DisableMeasureGroup "MeasureDriveK"][!SetOptionGroup DriveK Y 0R]
UpdateDivider=-1

[MeasureDriveFreeK]
Measure=FreeDiskSpace
Drive=K:
Group=MeasureDriveK
UpdateDivider=5

[MeasureDriveBusyK]
Measure=FreeDiskSpace
Drive=K:
Group=MeasureDriveK
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelL]
Measure=FreeDiskSpace
Drive=L:
Group=MeasureDriveL
Label=1
UpdateDivider=-1

[MeasureDriveTotalL]
Measure=FreeDiskSpace
Drive=L:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveL"][!EnableMeasureGroup "MeasureDriveL"][!SetOptionGroup DriveL Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveL"][!DisableMeasureGroup "MeasureDriveL"][!SetOptionGroup DriveL Y 0R]
UpdateDivider=-1

[MeasureDriveFreeL]
Measure=FreeDiskSpace
Drive=L:
Group=MeasureDriveL
UpdateDivider=5

[MeasureDriveBusyL]
Measure=FreeDiskSpace
Drive=L:
Group=MeasureDriveL
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelM]
Measure=FreeDiskSpace
Drive=M:
Group=MeasureDriveM
Label=1
UpdateDivider=-1

[MeasureDriveTotalM]
Measure=FreeDiskSpace
Drive=M:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveM"][!EnableMeasureGroup "MeasureDriveM"][!SetOptionGroup DriveM Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveM"][!DisableMeasureGroup "MeasureDriveM"][!SetOptionGroup DriveM Y 0R]
UpdateDivider=-1

[MeasureDriveFreeM]
Measure=FreeDiskSpace
Drive=M:
Group=MeasureDriveM
UpdateDivider=5

[MeasureDriveBusyM]
Measure=FreeDiskSpace
Drive=M:
Group=MeasureDriveM
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelN]
Measure=FreeDiskSpace
Drive=N:
Group=MeasureDriveN
Label=1
UpdateDivider=-1

[MeasureDriveTotalN]
Measure=FreeDiskSpace
Drive=N:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveN"][!EnableMeasureGroup "MeasureDriveN"][!SetOptionGroup DriveN Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveN"][!DisableMeasureGroup "MeasureDriveN"][!SetOptionGroup DriveN Y 0R]
UpdateDivider=-1

[MeasureDriveFreeN]
Measure=FreeDiskSpace
Drive=N:
Group=MeasureDriveN
UpdateDivider=5

[MeasureDriveBusyN]
Measure=FreeDiskSpace
Drive=N:
Group=MeasureDriveN
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelO]
Measure=FreeDiskSpace
Drive=O:
Group=MeasureDriveO
Label=1
UpdateDivider=-1

[MeasureDriveTotalO]
Measure=FreeDiskSpace
Drive=O:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveO"][!EnableMeasureGroup "MeasureDriveO"][!SetOptionGroup DriveO Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveO"][!DisableMeasureGroup "MeasureDriveO"][!SetOptionGroup DriveO Y 0R]
UpdateDivider=-1

[MeasureDriveFreeO]
Measure=FreeDiskSpace
Drive=O:
Group=MeasureDriveO
UpdateDivider=5

[MeasureDriveBusyO]
Measure=FreeDiskSpace
Drive=O:
Group=MeasureDriveO
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelP]
Measure=FreeDiskSpace
Drive=P:
Group=MeasureDriveP
Label=1
UpdateDivider=-1

[MeasureDriveTotalP]
Measure=FreeDiskSpace
Drive=P:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveP"][!EnableMeasureGroup "MeasureDriveP"][!SetOptionGroup DriveP Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveP"][!DisableMeasureGroup "MeasureDriveP"][!SetOptionGroup DriveP Y 0R]
UpdateDivider=-1

[MeasureDriveFreeP]
Measure=FreeDiskSpace
Drive=P:
Group=MeasureDriveP
UpdateDivider=5

[MeasureDriveBusyP]
Measure=FreeDiskSpace
Drive=P:
Group=MeasureDriveP
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelQ]
Measure=FreeDiskSpace
Drive=Q:
Group=MeasureDriveQ
Label=1
UpdateDivider=-1

[MeasureDriveTotalQ]
Measure=FreeDiskSpace
Drive=Q:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveQ"][!EnableMeasureGroup "MeasureDriveQ"][!SetOptionGroup DriveQ Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveQ"][!DisableMeasureGroup "MeasureDriveQ"][!SetOptionGroup DriveQ Y 0R]
UpdateDivider=-1

[MeasureDriveFreeQ]
Measure=FreeDiskSpace
Drive=Q:
Group=MeasureDriveQ
UpdateDivider=5

[MeasureDriveBusyQ]
Measure=FreeDiskSpace
Drive=Q:
Group=MeasureDriveQ
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelR]
Measure=FreeDiskSpace
Drive=R:
Group=MeasureDriveR
Label=1
UpdateDivider=-1

[MeasureDriveTotalR]
Measure=FreeDiskSpace
Drive=R:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveR"][!EnableMeasureGroup "MeasureDriveR"][!SetOptionGroup DriveR Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveR"][!DisableMeasureGroup "MeasureDriveR"][!SetOptionGroup DriveR Y 0R]
UpdateDivider=-1

[MeasureDriveFreeR]
Measure=FreeDiskSpace
Drive=R:
Group=MeasureDriveR
UpdateDivider=5

[MeasureDriveBusyR]
Measure=FreeDiskSpace
Drive=R:
Group=MeasureDriveR
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelS]
Measure=FreeDiskSpace
Drive=S:
Group=MeasureDriveS
Label=1
UpdateDivider=-1

[MeasureDriveTotalS]
Measure=FreeDiskSpace
Drive=S:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveS"][!EnableMeasureGroup "MeasureDriveS"][!SetOptionGroup DriveS Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveS"][!DisableMeasureGroup "MeasureDriveS"][!SetOptionGroup DriveS Y 0R]
UpdateDivider=-1

[MeasureDriveFreeS]
Measure=FreeDiskSpace
Drive=S:
Group=MeasureDriveS
UpdateDivider=5

[MeasureDriveBusyS]
Measure=FreeDiskSpace
Drive=S:
Group=MeasureDriveS
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelT]
Measure=FreeDiskSpace
Drive=T:
Group=MeasureDriveT
Label=1
UpdateDivider=-1

[MeasureDriveTotalT]
Measure=FreeDiskSpace
Drive=T:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveT"][!EnableMeasureGroup "MeasureDriveT"][!SetOptionGroup DriveT Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveT"][!DisableMeasureGroup "MeasureDriveT"][!SetOptionGroup DriveT Y 0R]
UpdateDivider=-1

[MeasureDriveFreeT]
Measure=FreeDiskSpace
Drive=T:
Group=MeasureDriveT
UpdateDivider=5

[MeasureDriveBusyT]
Measure=FreeDiskSpace
Drive=T:
Group=MeasureDriveT
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelU]
Measure=FreeDiskSpace
Drive=U:
Group=MeasureDriveU
Label=1
UpdateDivider=-1

[MeasureDriveTotalU]
Measure=FreeDiskSpace
Drive=U:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveU"][!EnableMeasureGroup "MeasureDriveU"][!SetOptionGroup DriveU Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveU"][!DisableMeasureGroup "MeasureDriveU"][!SetOptionGroup DriveU Y 0R]
UpdateDivider=-1

[MeasureDriveFreeU]
Measure=FreeDiskSpace
Drive=U:
Group=MeasureDriveU
UpdateDivider=5

[MeasureDriveBusyU]
Measure=FreeDiskSpace
Drive=U:
Group=MeasureDriveU
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelV]
Measure=FreeDiskSpace
Drive=V:
Group=MeasureDriveV
Label=1
UpdateDivider=-1

[MeasureDriveTotalV]
Measure=FreeDiskSpace
Drive=V:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveV"][!EnableMeasureGroup "MeasureDriveV"][!SetOptionGroup DriveV Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveV"][!DisableMeasureGroup "MeasureDriveV"][!SetOptionGroup DriveV Y 0R]
UpdateDivider=-1

[MeasureDriveFreeV]
Measure=FreeDiskSpace
Drive=V:
Group=MeasureDriveV
UpdateDivider=5

[MeasureDriveBusyV]
Measure=FreeDiskSpace
Drive=V:
Group=MeasureDriveV
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelW]
Measure=FreeDiskSpace
Drive=W:
Group=MeasureDriveW
Label=1
UpdateDivider=-1

[MeasureDriveTotalW]
Measure=FreeDiskSpace
Drive=W:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveW"][!EnableMeasureGroup "MeasureDriveW"][!SetOptionGroup DriveW Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveW"][!DisableMeasureGroup "MeasureDriveW"][!SetOptionGroup DriveW Y 0R]
UpdateDivider=-1

[MeasureDriveFreeW]
Measure=FreeDiskSpace
Drive=W:
Group=MeasureDriveW
UpdateDivider=5

[MeasureDriveBusyW]
Measure=FreeDiskSpace
Drive=W:
Group=MeasureDriveW
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelX]
Measure=FreeDiskSpace
Drive=X:
Group=MeasureDriveX
Label=1
UpdateDivider=-1

[MeasureDriveTotalX]
Measure=FreeDiskSpace
Drive=X:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveX"][!EnableMeasureGroup "MeasureDriveX"][!SetOptionGroup DriveX Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveX"][!DisableMeasureGroup "MeasureDriveX"][!SetOptionGroup DriveX Y 0R]
UpdateDivider=-1

[MeasureDriveFreeX]
Measure=FreeDiskSpace
Drive=X:
Group=MeasureDriveX
UpdateDivider=5

[MeasureDriveBusyX]
Measure=FreeDiskSpace
Drive=X:
Group=MeasureDriveX
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelY]
Measure=FreeDiskSpace
Drive=Y:
Group=MeasureDriveY
Label=1
UpdateDivider=-1

[MeasureDriveTotalY]
Measure=FreeDiskSpace
Drive=Y:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveY"][!EnableMeasureGroup "MeasureDriveY"][!SetOptionGroup DriveY Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveY"][!DisableMeasureGroup "MeasureDriveY"][!SetOptionGroup DriveY Y 0R]
UpdateDivider=-1

[MeasureDriveFreeY]
Measure=FreeDiskSpace
Drive=Y:
Group=MeasureDriveY
UpdateDivider=5

[MeasureDriveBusyY]
Measure=FreeDiskSpace
Drive=Y:
Group=MeasureDriveY
InvertMeasure=1
UpdateDivider=5

[MeasureDriveLabelZ]
Measure=FreeDiskSpace
Drive=Z:
Group=MeasureDriveZ
Label=1
UpdateDivider=-1

[MeasureDriveTotalZ]
Measure=FreeDiskSpace
Drive=Z:
Total=1
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup "DriveZ"][!EnableMeasureGroup "MeasureDriveZ"][!SetOptionGroup DriveZ Y ""]
IfEqualValue=0
IfEqualAction=[!HideMeterGroup "DriveZ"][!DisableMeasureGroup "MeasureDriveZ"][!SetOptionGroup DriveZ Y 0R]
UpdateDivider=-1

[MeasureDriveFreeZ]
Measure=FreeDiskSpace
Drive=Z:
Group=MeasureDriveZ
UpdateDivider=5

[MeasureDriveBusyZ]
Measure=FreeDiskSpace
Drive=Z:
Group=MeasureDriveZ
InvertMeasure=1
UpdateDivider=5